/// Zylith Verifier Interface
///
/// Defines the interface for Garaga-generated Groth16 proof verifiers on BN254.
/// Each circuit type (membership, swap, mint, burn) has its own verifier
/// contract generated by `garaga gen`.
///
/// ## Integration
///
/// Verifier contracts are generated by Garaga CLI and deployed independently.
/// The coordinator dispatches proofs to the appropriate verifier contract.
///
/// ## Proof Format
///
/// `full_proof_with_hints` is a serialized blob generated by `garaga calldata`
/// containing the Groth16 proof, public inputs, MSM hints, and pairing hints.

/// Garaga-generated Groth16 verifier interface for BN254 curve
///
/// This matches the interface generated by `garaga gen --system groth16`.
/// Each verifier contract embeds its circuit-specific verification key.
#[starknet::interface]
pub trait IGroth16VerifierBN254<TContractState> {
    /// Verify a Groth16 proof on BN254 with precomputed hints
    ///
    /// # Arguments
    /// * `full_proof_with_hints` - Serialized proof + public inputs + MSM/pairing hints
    ///   Generated by `garaga calldata` tool
    ///
    /// # Returns
    /// * `Result::Ok(public_inputs)` - Public inputs as Span<u256> if proof is valid
    /// * `Result::Err(error)` - Error message if proof is invalid
    fn verify_groth16_proof_bn254(
        self: @TContractState, full_proof_with_hints: Span<felt252>,
    ) -> Result<Span<u256>, felt252>;
}
